/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author 44ong
 */
public class LapHoaDonGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public LapHoaDonGUI() {
    	
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel_left = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_tongquan = new javax.swing.JPanel();
        label_tongquan = new javax.swing.JLabel();
        panel_capnhat = new javax.swing.JPanel();
        label_capnhat = new javax.swing.JLabel();
        panel_hoadon = new javax.swing.JPanel();
        label_hoadon = new javax.swing.JLabel();
        panel_laphoadon = new javax.swing.JPanel();
        label_laphoadon = new javax.swing.JLabel();
        panel_doanhthu = new javax.swing.JPanel();
        label_doanhthu = new javax.swing.JLabel();
        panel_nhapthuoc = new javax.swing.JPanel();
        label_nhapthuoc = new javax.swing.JLabel();
        panel_dangxuat = new javax.swing.JPanel();
        label_dangxuat = new javax.swing.JLabel();
        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_right = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel_thongtin = new javax.swing.JPanel();
        label_tenkhachhang = new javax.swing.JLabel();
        field_tenkhachhang = new javax.swing.JTextField();
        label_sdt = new javax.swing.JLabel();
        field_sdt = new javax.swing.JTextField();
        label_diachi = new javax.swing.JLabel();
        field_diachi = new javax.swing.JTextField();
        label_tennhanvien = new javax.swing.JLabel();
        field_tennhanvien = new javax.swing.JTextField();
        label_ngayban = new javax.swing.JLabel();
        field_ngayban = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        panel_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        panel_sanpham = new javax.swing.JPanel();
        panel_thongtinsanpham = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panel_hinhanhsanpham = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panel_timkiem = new javax.swing.JPanel();
        field_timkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panel_button = new javax.swing.JPanel();
        button_them = new javax.swing.JButton();
        button_xoa = new javax.swing.JButton();
        button_luu = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_left.setBackground(new java.awt.Color(4, 71, 126));
        panel_left.setPreferredSize(new java.awt.Dimension(200, 470));
        panel_left.setLayout(new java.awt.GridLayout(8, 1));

        panel_logo.setBackground(new java.awt.Color(4, 71, 126));
        panel_logo.setLayout(new java.awt.BorderLayout());

        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logobenvien_resize.png"))); // NOI18N
        label_logo.setText("jLabel1");
        label_logo.setPreferredSize(new java.awt.Dimension(70, 62));
        panel_logo.add(label_logo, java.awt.BorderLayout.LINE_START);

        panel_left.add(panel_logo);

        panel_tongquan.setBackground(new java.awt.Color(4, 71, 126));
        panel_tongquan.setLayout(new java.awt.BorderLayout());

        label_tongquan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_tongquan.setForeground(new java.awt.Color(255, 255, 255));
        label_tongquan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tongquan.setText("Tổng Quan");
        label_tongquan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_tongquanMouseClicked(evt);
            }
        });
        panel_tongquan.add(label_tongquan, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_tongquan);

        panel_capnhat.setBackground(new java.awt.Color(4, 71, 126));
        panel_capnhat.setLayout(new java.awt.BorderLayout());

        label_capnhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_capnhat.setForeground(new java.awt.Color(255, 255, 255));
        label_capnhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_capnhat.setText("Cập Nhật");
        label_capnhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_capnhatMouseClicked(evt);
            }
        });
        panel_capnhat.add(label_capnhat, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_capnhat);

        panel_hoadon.setBackground(new java.awt.Color(4, 71, 126));
        panel_hoadon.setLayout(new java.awt.BorderLayout());

        label_hoadon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_hoadon.setForeground(new java.awt.Color(255, 255, 255));
        label_hoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_hoadon.setText("Hóa Đơn");
        label_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_hoadonMouseClicked(evt);
            }
        });
        panel_hoadon.add(label_hoadon, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_hoadon);

        panel_laphoadon.setBackground(new java.awt.Color(32, 86, 161));
        panel_laphoadon.setLayout(new java.awt.BorderLayout());

        label_laphoadon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_laphoadon.setForeground(new java.awt.Color(255, 255, 255));
        label_laphoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_laphoadon.setText("Lập Hóa Đơn");
        label_laphoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_laphoadonMouseClicked(evt);
            }
        });
        panel_laphoadon.add(label_laphoadon, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_laphoadon);

        panel_doanhthu.setBackground(new java.awt.Color(4, 71, 126));
        panel_doanhthu.setLayout(new java.awt.BorderLayout());

        label_doanhthu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_doanhthu.setForeground(new java.awt.Color(255, 255, 255));
        label_doanhthu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_doanhthu.setText("Doanh Thu");
        label_doanhthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_doanhthuMouseClicked(evt);
            }
        });
        panel_doanhthu.add(label_doanhthu, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_doanhthu);

        panel_nhapthuoc.setBackground(new java.awt.Color(4, 71, 126));
        panel_nhapthuoc.setLayout(new java.awt.BorderLayout());

        label_nhapthuoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_nhapthuoc.setForeground(new java.awt.Color(255, 255, 255));
        label_nhapthuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nhapthuoc.setText("Nhập Thuốc");
        label_nhapthuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_nhapthuocMouseClicked(evt);
            }
        });
        panel_nhapthuoc.add(label_nhapthuoc, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_nhapthuoc);

        panel_dangxuat.setBackground(new java.awt.Color(4, 71, 126));
        panel_dangxuat.setLayout(new java.awt.BorderLayout());

        label_dangxuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        label_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dangxuat.setText("Đăng Xuất");
        label_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dangxuatMouseClicked(evt);
            }
        });
        panel_dangxuat.add(label_dangxuat, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_dangxuat);

        getContentPane().add(panel_left, java.awt.BorderLayout.LINE_START);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_right.setForeground(new java.awt.Color(255, 255, 255));
        panel_right.setPreferredSize(new java.awt.Dimension(700, 470));
        panel_right.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        panel_thongtin.setLayout(new java.awt.GridBagLayout());

        label_tenkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_tenkhachhang.setText("Tên Khách Hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(label_tenkhachhang, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(field_tenkhachhang, gridBagConstraints);

        label_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_sdt.setText("Số Điện Thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(label_sdt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(field_sdt, gridBagConstraints);

        label_diachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_diachi.setText("Địa Chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(label_diachi, gridBagConstraints);

        field_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_diachiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(field_diachi, gridBagConstraints);

        label_tennhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_tennhanvien.setText("Tên Nhân Viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(label_tennhanvien, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(field_tennhanvien, gridBagConstraints);

        label_ngayban.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_ngayban.setText("Ngày Bán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(label_ngayban, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(field_ngayban, gridBagConstraints);

        jLabel6.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin.add(jTextField6, gridBagConstraints);

        jPanel1.add(panel_thongtin);

        panel_table.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Thuốc", "Tên Thuốc", "Số Lượng", "Giá"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel_table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel_table);

        panel_right.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        panel_sanpham.setLayout(new java.awt.GridLayout(2, 1));

        panel_thongtinsanpham.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Mã Thuốc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(jLabel1, gridBagConstraints);

        jLabel2.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Tên Thuốc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(jLabel3, gridBagConstraints);

        jLabel4.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Hàm Lượng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(jLabel5, gridBagConstraints);

        jLabel7.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel7, gridBagConstraints);

        jLabel9.setText("Phân Loại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(jLabel9, gridBagConstraints);

        jLabel10.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Giá TIền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(jLabel11, gridBagConstraints);

        jLabel12.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel12, gridBagConstraints);

        jLabel14.setText("Đơn Vị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(jLabel14, gridBagConstraints);

        jLabel15.setText("jLabel15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel15, gridBagConstraints);

        jLabel16.setText("Thành Phần Chính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(jLabel16, gridBagConstraints);

        jLabel17.setText("jLabel17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel17, gridBagConstraints);

        jLabel19.setText("Ngày Hết Hạn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(jLabel19, gridBagConstraints);

        jLabel20.setText("jLabel20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(jLabel20, gridBagConstraints);

        panel_sanpham.add(panel_thongtinsanpham);

        panel_hinhanhsanpham.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Picture1.png"))); // NOI18N
        panel_hinhanhsanpham.add(jLabel18, java.awt.BorderLayout.CENTER);

        panel_sanpham.add(panel_hinhanhsanpham);

        jPanel2.add(panel_sanpham, java.awt.BorderLayout.CENTER);

        panel_timkiem.setPreferredSize(new java.awt.Dimension(350, 30));
        panel_timkiem.setLayout(new java.awt.BorderLayout());

        field_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_timkiemActionPerformed(evt);
            }
        });
        panel_timkiem.add(field_timkiem, java.awt.BorderLayout.CENTER);

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_timkiem.add(jButton1, java.awt.BorderLayout.LINE_END);

        jPanel2.add(panel_timkiem, java.awt.BorderLayout.PAGE_START);

        panel_button.setLayout(new java.awt.GridBagLayout());

        button_them.setText("Thêm");
        button_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_themActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(40, 31, 37, 25);
        panel_button.add(button_them, gridBagConstraints);

        button_xoa.setText("Xóa");
        button_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_xoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 31, 37, 25);
        panel_button.add(button_xoa, gridBagConstraints);

        button_luu.setText("Lưu");
        button_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_luuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 31, 37, 25);
        panel_button.add(button_luu, gridBagConstraints);

        jPanel2.add(panel_button, java.awt.BorderLayout.PAGE_END);

        panel_right.add(jPanel2);

        getContentPane().add(panel_right, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(976, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=LapHoaDonGUI.MAXIMIZED_BOTH){
            this.setExtendedState(LapHoaDonGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(LapHoaDonGUI.NORMAL);
        }  
    }                                             

    private void label_tongquanMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    	this.setVisible(false);
    	TongQuanGUI tongquangui = new TongQuanGUI();
    	tongquangui.setVisible(true);
    }                                           

    private void label_capnhatMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void label_hoadonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonGUI hoadongui = new HoaDonGUI();
        hoadongui.setVisible(true);
    }                                         

    private void label_laphoadonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void label_doanhthuMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void label_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {                                            
        this.setVisible(false);
        LoginForm loginform = new LoginForm();
        loginform.setVisible(true);
    }                                           

    private void field_diachiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void button_themActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void button_xoaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_luuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void field_timkiemActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void label_nhapthuocMouseClicked(java.awt.event.MouseEvent evt) {                                             
        this.setVisible(false);
        NhapThuocGUI nhapthuocgui = new NhapThuocGUI();
        nhapthuocgui.setVisible(true);
        		
    }                                            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapHoaDonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button_luu;
    private javax.swing.JButton button_them;
    private javax.swing.JButton button_xoa;
    private javax.swing.JTextField field_diachi;
    private javax.swing.JTextField field_ngayban;
    private javax.swing.JTextField field_sdt;
    private javax.swing.JTextField field_tenkhachhang;
    private javax.swing.JTextField field_tennhanvien;
    private javax.swing.JTextField field_timkiem;
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel label_capnhat;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_dangxuat;
    private javax.swing.JLabel label_diachi;
    private javax.swing.JLabel label_doanhthu;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_hoadon;
    private javax.swing.JLabel label_laphoadon;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_ngayban;
    private javax.swing.JLabel label_nhapthuoc;
    private javax.swing.JLabel label_sdt;
    private javax.swing.JLabel label_tenkhachhang;
    private javax.swing.JLabel label_tennhanvien;
    private javax.swing.JLabel label_tongquan;
    private javax.swing.JPanel panel_button;
    private javax.swing.JPanel panel_capnhat;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_dangxuat;
    private javax.swing.JPanel panel_doanhthu;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_hinhanhsanpham;
    private javax.swing.JPanel panel_hoadon;
    private javax.swing.JPanel panel_laphoadon;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_nhapthuoc;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel panel_sanpham;
    private javax.swing.JPanel panel_table;
    private javax.swing.JPanel panel_thongtin;
    private javax.swing.JPanel panel_thongtinsanpham;
    private javax.swing.JPanel panel_timkiem;
    private javax.swing.JPanel panel_tongquan;
    // End of variables declaration                   
}
