/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Base64;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import Controller.QuanLyThuocController;


/**
 *
 * @author 44ong
 */
public class NhapThuocGUI extends javax.swing.JFrame {

   


	/**
     * Creates new form MainForm
     */
    public NhapThuocGUI() {
    	this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        label_quanlythuoc = new javax.swing.JLabel();
        panel_thongtin = new javax.swing.JPanel();
        panel_thanhsearch_button = new javax.swing.JPanel();
        panel_button_filter = new javax.swing.JPanel();
        button_search = new javax.swing.JButton();
        cb_filter = new javax.swing.JComboBox<>();
        field_search = new javax.swing.JTextField();
        panel_nhapthuoc = new javax.swing.JPanel();
        panel_button = new javax.swing.JPanel();
        panel_contain_button = new javax.swing.JPanel();
        button_them = new javax.swing.JButton();
        button_xoa = new javax.swing.JButton();
        button_hoantac = new javax.swing.JButton();
        button_thoat = new javax.swing.JButton();
        panel_field_nhapthuoc_table = new javax.swing.JPanel();
        panel_field_nhapthuoc = new javax.swing.JPanel();
        label_mathuoc = new javax.swing.JLabel();
        field_mathuoc = new javax.swing.JTextField();
        label_tenthuoc = new javax.swing.JLabel();
        field_tenthuoc = new javax.swing.JTextField();
        label_ngaynhap = new javax.swing.JLabel();
        field_ngaynhap = new javax.swing.JTextField();
        label_ngayhethan = new javax.swing.JLabel();
        field_ngayhethan = new javax.swing.JTextField();
        label_gia = new javax.swing.JLabel();
        field_gia = new javax.swing.JTextField();
        label_soluong = new javax.swing.JLabel();
        field_soluong = new javax.swing.JTextField();
        label_phanloai = new javax.swing.JLabel();
        label_hinhanh = new javax.swing.JLabel();
        label_hamluong = new javax.swing.JLabel();
        field_hamluong = new javax.swing.JTextField();
        label_donvitinh = new javax.swing.JLabel();
        button_hinhanh = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        field_phanloai = new javax.swing.JTextField();
        panel_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        lblImagePreview = new javax.swing.JLabel();
        
        
        quanLyThuocController = new QuanLyThuocController();
        
        
        

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_main.setLayout(new java.awt.BorderLayout());

        panel_title.setBackground(new java.awt.Color(4, 71, 126));
        panel_title.setPreferredSize(new java.awt.Dimension(100, 100));
        panel_title.setLayout(new java.awt.BorderLayout());

        label_quanlythuoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlythuoc.setForeground(new java.awt.Color(255, 255, 255));
        label_quanlythuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlythuoc.setText("Quản Lý Thuốc");
        panel_title.add(label_quanlythuoc, java.awt.BorderLayout.CENTER);

        panel_main.add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_thongtin.setLayout(new java.awt.BorderLayout());

        panel_thanhsearch_button.setPreferredSize(new java.awt.Dimension(900, 60));
        panel_thanhsearch_button.setLayout(new java.awt.BorderLayout());

        panel_button_filter.setPreferredSize(new java.awt.Dimension(200, 50));
        panel_button_filter.setLayout(new java.awt.GridLayout(1, 2));

        button_search.setBackground(new java.awt.Color(4, 71, 126));
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("Tìm");
        button_search.setToolTipText("");
        button_search.setActionCommand("");
        button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_searchMouseClicked(evt);
            }
        });
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });
        panel_button_filter.add(button_search);

        cb_filter.setBackground(new java.awt.Color(4, 71, 126));
        cb_filter.setForeground(new java.awt.Color(255, 255, 255));
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên", "Chức Năng", "Thành Phần" }));
        panel_button_filter.add(cb_filter);

        panel_thanhsearch_button.add(panel_button_filter, java.awt.BorderLayout.LINE_END);

        field_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        field_search.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        field_search.setPreferredSize(new java.awt.Dimension(64, 55));
        panel_thanhsearch_button.add(field_search, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_thanhsearch_button, java.awt.BorderLayout.PAGE_START);

        panel_nhapthuoc.setLayout(new java.awt.BorderLayout());

        panel_button.setBackground(new java.awt.Color(255, 255, 255));
        panel_button.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_button.setLayout(new java.awt.BorderLayout());

        panel_contain_button.setBackground(new java.awt.Color(255, 255, 255));
        panel_contain_button.setPreferredSize(new java.awt.Dimension(550, 50));
        panel_contain_button.setLayout(new java.awt.GridBagLayout());

        button_them.setText("Thêm ");
        button_them.setActionCommand("Thêm");
        button_them.setPreferredSize(new java.awt.Dimension(120, 26));
        button_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_taohaodonMouseClicked(evt);
            }
        });
        button_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_themActionPerformed(evt);
            }


        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_them, gridBagConstraints);

        button_xoa.setText("Xóa");
        button_xoa.setPreferredSize(new java.awt.Dimension(120, 26));
        button_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_xoaMouseClicked(evt);
            }
        });
        button_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_xoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_xoa, gridBagConstraints);

        button_hoantac.setText("Hoàn Tác");
        button_hoantac.setPreferredSize(new java.awt.Dimension(120, 26));
        button_hoantac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_hoantacMouseClicked(evt);
            }
        });
        button_hoantac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hoantacActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_hoantac, gridBagConstraints);

        button_thoat.setText("Thoát");
        button_thoat.setPreferredSize(new java.awt.Dimension(120, 26));
        button_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_thoatMouseClicked(evt);
            }
        });
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        panel_contain_button.add(button_thoat, gridBagConstraints);

        panel_button.add(panel_contain_button, java.awt.BorderLayout.LINE_END);

        panel_nhapthuoc.add(panel_button, java.awt.BorderLayout.PAGE_START);

        panel_field_nhapthuoc_table.setLayout(new java.awt.GridLayout(2, 1));

        panel_field_nhapthuoc.setLayout(new java.awt.GridBagLayout());

        label_mathuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_mathuoc.setText("Mã Thuốc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_mathuoc, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_mathuoc, gridBagConstraints);

        label_tenthuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_tenthuoc.setText("Tên Thuốc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_tenthuoc, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_tenthuoc, gridBagConstraints);

        label_ngaynhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_ngaynhap.setText("Ngày Nhập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_ngaynhap, gridBagConstraints);

        field_ngaynhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_ngaynhapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_ngaynhap, gridBagConstraints);

        label_ngayhethan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_ngayhethan.setText("Ngày Hết Hạn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_ngayhethan, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_ngayhethan, gridBagConstraints);

        label_gia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_gia.setText("Giá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_gia, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_gia, gridBagConstraints);

        label_soluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_soluong.setText("Số Lượng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_soluong, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_soluong, gridBagConstraints);

        label_phanloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_phanloai.setText("Phân Loại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_phanloai, gridBagConstraints);

        label_hinhanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_hinhanh.setText("Hình Ảnh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_hinhanh, gridBagConstraints);

        label_hamluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_hamluong.setText("Hàm Lượng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_hamluong, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_hamluong, gridBagConstraints);

        label_donvitinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_donvitinh.setText("Đơn Vị Tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(label_donvitinh, gridBagConstraints);

        button_hinhanh.setText("Upload");
        button_hinhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_hinhanhMouseClicked(evt);
            }
        });
        button_hinhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hinhanhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(button_hinhanh, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hộp", "Vỉ", "Viên", "Chai" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(jComboBox2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_field_nhapthuoc.add(field_phanloai, gridBagConstraints);

        panel_field_nhapthuoc_table.add(panel_field_nhapthuoc);

        panel_table.setLayout(new java.awt.BorderLayout());

        
        
        String[] columnNames = {
                "Mã Thuốc", "Tên Thuốc","Hình Ảnh", "Ngày Nhập" ,"Ngày Hết Hạn", "Giá", "Số Lương", "Phân Loại", "Đơn Vị Tính", "Hàm Lượng"
            }
        ;
        
        Object[][] data = {
                {null, null,null, null, null, null, null, null, null, null},
                {null, null,null, null, null, null, null, null, null, null},
                {null, null,null, null, null, null, null, null, null, null},
                {null, null,null, null, null, null, null, null, null, null}
            };
        
        
         tableModel = new DefaultTableModel(data, columnNames);
        jTable1.setModel(tableModel);
       /* jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null,null, null, null, null, null, null, null, null},
                {null, null,null, null, null, null, null, null, null, null},
                {null, null,null, null, null, null, null, null, null, null},
                {null, null,null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thuốc", "Tên Thuốc","Hình Ảnh", "Ngày Nhập" ,"Ngày Hết Hạn", "Giá", "Số Lương", "Phân Loại", "Đơn Vị Tính", "Hàm Lượng"
            }
        ));*/
        jScrollPane1.setViewportView(jTable1);

        panel_table.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panel_field_nhapthuoc_table.add(panel_table);

        panel_nhapthuoc.add(panel_field_nhapthuoc_table, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_nhapthuoc, java.awt.BorderLayout.CENTER);
        
        
        
        
        
        
        
        
        
        MenuForm_2 menuForm_2 = new MenuForm_2(new MenuForm_2.MenuListener() {
            
        	/*@Override public void onDrugImportSelected() { showFrame(new DrugImportFrame()); }
            @Override public void onDrugUpdateSelected() { showFrame(new DrugUpdateFrame()); }
            @Override public void onDrugListSelected() { showFrame(new DrugListFrame()); }
            @Override public void onInvoiceCreateSelected() { showFrame(new InvoiceCreateFrame()); }
            @Override public void onInvoiceListSelected() { showFrame(new InvoiceListFrame()); }
            @Override public void onRevenueStatsSelected() { showFrame(new RevenueStatsFrame()); }
            @Override public void onDrugStatsSelected() { showFrame(new DrugStatsFrame()); }
            @Override public void onStaffListSelected() { showFrame(new StaffListFrame()); }
            @Override public void onAddStaffSelected() { showFrame(new AddStaffFrame()); }
            @Override public void onCustomerListSelected() { showFrame(new CustomerListFrame()); }
            @Override public void onAddCustomerSelected() { showFrame(new AddCustomerFrame()); }
            @Override public void onSupplierListSelected() { showFrame(new SupplierListFrame()); }
            @Override public void onAddSupplierSelected() { showFrame(new AddSupplierFrame()); }*/
        	
        	
        	
        	
        	
        	@Override public void openFormNhapThuoc() { showFrame(new NhapThuocGUI()); }
            @Override public void openFormCapNhatThuoc() { showFrame(new DrugUpdateFrame()); }
            @Override public void openFormDanhSachThuoc() { showFrame(new QuanLyThuocGUI()); }
            @Override public void openFormTaoHoaDon() { showFrame(new TaoHoaDonGUI()); }
            @Override public void openFormDanhSachHoaDon() { showFrame(new QuanLyHoaDonGUI()); }
            @Override public void openFormThongKeDoanhThu() { showFrame(new ThongKeDoanhThuGUI()); }
            @Override public void openFormThongKeThuoc() { showFrame(new ThongKeThuocGUI()); }
            @Override public void openFormDanhSachNhanVien() { showFrame(new QuanLyNhanVienGUI()); }
            @Override public void openFormThemNhanVien() { showFrame(new AddStaffFrame()); }
            @Override public void openFormDanhSachKhachHang() { showFrame(new CustomerListFrame()); }
            @Override public void openFormThemKhachHang() { showFrame(new AddCustomerFrame()); }
            @Override public void openFormNhaCungCap() { showFrame(new SupplierListFrame()); }
            @Override public void openFormThemNhaCungCap() { showFrame(new AddSupplierFrame()); }
        	
        });
        
        
        
        
        
        panel_main.add(menuForm_2, java.awt.BorderLayout.WEST);
       

        panel_main.add(panel_thongtin, java.awt.BorderLayout.CENTER);
        
        
    

        getContentPane().add(panel_main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=NhapThuocGUI.MAXIMIZED_BOTH){
            this.setExtendedState(NhapThuocGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(NhapThuocGUI.NORMAL);
        }  
    }     
    
    
	private void button_themActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		try {
			
			String maThuoc = field_mathuoc.getText();
            String tenThuoc = field_tenthuoc.getText();
            //String hinhAnh = button_hinhanh.getText();
            String ngayNhap = field_ngaynhap.getText();
            String ngayHetHan = field_ngayhethan.getText();
            int soLuong = Integer.parseInt(field_soluong.getText());
            String donViTinh = jComboBox2.getSelectedItem().toString();
            double donGia = Double.parseDouble(field_gia.getText());
            String phanLoai = field_phanloai.getText();
            double hamLuong = Double.parseDouble(field_hamluong.getText())  ;
            
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            
            LocalDate ngayNhap_date = LocalDate.parse(ngayNhap, formatter);
            LocalDate ngayHetHan_date = LocalDate.parse(ngayHetHan, formatter);
            
 
            
            String hinhAnh ="";
            if(lblImagePreview.getIcon()!=null) {
            	ImageIcon icon = (ImageIcon) lblImagePreview.getIcon();
            	hinhAnh = encodeImageToBase64(icon.getImage());
            }
            
            
            // Cần handling Hình ảnh ở đây
            boolean success = quanLyThuocController.themThuoc(maThuoc,  tenThuoc,  hinhAnh,  ngayNhap_date,  ngayHetHan_date,  soLuong,
					 donViTinh,  donGia,  phanLoai,  hamLuong,  tableModel);
            if(success) {
            	JOptionPane.showMessageDialog(null, "Thêm thuốc thành công");
            	
            }else {
            	JOptionPane.showMessageDialog(null, "Thêm thuốc thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
			
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null, "Dữ liệu nhập không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
		}
		
	}
	
	// handle image
	private String encodeImageToBase64(Image image) {
	    try {
	        BufferedImage bufferedImage = new BufferedImage(
	            image.getWidth(null), image.getHeight(null), 
	            BufferedImage.TYPE_INT_RGB
	        );
	        
	        Graphics2D g2d = bufferedImage.createGraphics();
	        g2d.drawImage(image, 0, 0, null);
	        g2d.dispose();
	        
	        ByteArrayOutputStream baos = new ByteArrayOutputStream();
	        ImageIO.write(bufferedImage, "jpg", baos);
	        byte[] imageBytes = baos.toByteArray();
	        
	        return Base64.getEncoder().encodeToString(imageBytes);
	    } catch (IOException e) {
	        JOptionPane.showMessageDialog(null, "Lỗi khi xử lý hình ảnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
	        return "";
	    }
	}
	
	
	
	// Image upload button handler
	private void btnUploadImageActionPerformed(ActionEvent evt) {
	    JFileChooser fileChooser = new JFileChooser();
	    fileChooser.setDialogTitle("Chọn hình ảnh thuốc");
	    
	    // Filter for image files only
	    fileChooser.setAcceptAllFileFilterUsed(false);
	    fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(
	        "Image files", ImageIO.getReaderFileSuffixes()));
	    
	    int returnValue = fileChooser.showOpenDialog(this);
	    if (returnValue == JFileChooser.APPROVE_OPTION) {
	        File selectedFile = fileChooser.getSelectedFile();
	        try {
	            // Create and scale the image for preview
	            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
	            Image scaledImage = icon.getImage().getScaledInstance(
	                150, 150, Image.SCALE_SMOOTH);
	            lblImagePreview.setIcon(new ImageIcon(scaledImage));
	            
	            // Optional: Store the original file path if needed
	            // button_hinhanh.setText(selectedFile.getAbsolutePath());
	        } catch (Exception ex) {
	            JOptionPane.showMessageDialog(this, 
	                "Không thể tải hình ảnh: " + ex.getMessage(), 
	                "Lỗi", JOptionPane.ERROR_MESSAGE);
	        }
	    }
	}
	
	
	
	
	
	
	
	
	

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void button_searchMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_taohaodonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void button_taohaodonMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void button_xoaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_xoaMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void button_hoantacActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void button_hoantacMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void button_thoatMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	this.setVisible(false);
    	QuanLyThuocGUI quanlythuocgui = new QuanLyThuocGUI();
    	quanlythuocgui.setVisible(true);
    }                                         

    private void field_ngaynhapActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void button_hinhanhActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	
    	
    }                                              

    private void button_hinhanhMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapThuocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button_hinhanh;
    private javax.swing.JButton button_hoantac;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_them;
    private javax.swing.JButton button_thoat;
    private javax.swing.JButton button_xoa;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JTextField field_gia;
    private javax.swing.JTextField field_hamluong;
    private javax.swing.JTextField field_mathuoc;
    private javax.swing.JTextField field_ngayhethan;
    private javax.swing.JTextField field_ngaynhap;
    private javax.swing.JTextField field_phanloai;
    private javax.swing.JTextField field_search;
    private javax.swing.JTextField field_soluong;
    private javax.swing.JTextField field_tenthuoc;
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_donvitinh;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_gia;
    private javax.swing.JLabel label_hamluong;
    private javax.swing.JLabel label_hinhanh;
    private javax.swing.JLabel label_mathuoc;
    private javax.swing.JLabel label_ngayhethan;
    private javax.swing.JLabel label_ngaynhap;
    private javax.swing.JLabel label_phanloai;
    private javax.swing.JLabel label_quanlythuoc;
    private javax.swing.JLabel label_soluong;
    private javax.swing.JLabel label_tenthuoc;
    private javax.swing.JPanel panel_button;
    private javax.swing.JPanel panel_button_filter;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_contain_button;
    private javax.swing.JPanel panel_field_nhapthuoc;
    private javax.swing.JPanel panel_field_nhapthuoc_table;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_nhapthuoc;
    private javax.swing.JPanel panel_table;
    private javax.swing.JPanel panel_thanhsearch_button;
    private javax.swing.JPanel panel_thongtin;
    private javax.swing.JPanel panel_title;
    
    private QuanLyThuocController quanLyThuocController;
    private DefaultTableModel tableModel;
    
    private javax.swing.JLabel lblImagePreview;
    
    
    // End of variables declaration 
    
    private void showFrame(JFrame frame) {
    	this.setVisible(false);
        frame.setVisible(true);
    }
}
