/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author 44ong
 */
public class QuanLyHoaDonGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public QuanLyHoaDonGUI() {
    	this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        label_quanlyhoadon = new javax.swing.JLabel();
        panel_thongtin = new javax.swing.JPanel();
        panel_thanhsearch_button = new javax.swing.JPanel();
        panel_button_filter = new javax.swing.JPanel();
        button_search = new javax.swing.JButton();
        cb_filter = new javax.swing.JComboBox<>();
        field_search = new javax.swing.JTextField();
        panel_hoadon = new javax.swing.JPanel();
        panel_taohoadon = new javax.swing.JPanel();
        panel_contain_button = new javax.swing.JPanel();
        button_taohaodon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button_thoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_chitiethoadon = new javax.swing.JPanel();
        panel_title_chitiethoadon = new javax.swing.JPanel();
        label_chitiethoadon = new javax.swing.JLabel();
        panel_thongtin_chitiethoadon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panel_tonghoadon = new javax.swing.JPanel();
        label_thue = new javax.swing.JLabel();
        giatrithue = new javax.swing.JLabel();
        label_tongtienhoadon = new javax.swing.JLabel();
        tongtien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_main.setLayout(new java.awt.BorderLayout());

        panel_title.setBackground(new java.awt.Color(4, 71, 126));
        panel_title.setPreferredSize(new java.awt.Dimension(100, 100));
        panel_title.setLayout(new java.awt.BorderLayout());

        label_quanlyhoadon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlyhoadon.setForeground(new java.awt.Color(255, 255, 255));
        label_quanlyhoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlyhoadon.setText("Quản Lý Hóa Đơn");
        panel_title.add(label_quanlyhoadon, java.awt.BorderLayout.CENTER);

        panel_main.add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_thongtin.setLayout(new java.awt.BorderLayout());

        panel_thanhsearch_button.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_thanhsearch_button.setLayout(new java.awt.BorderLayout());

        panel_button_filter.setPreferredSize(new java.awt.Dimension(200, 50));
        panel_button_filter.setLayout(new java.awt.GridLayout(1, 2));

        button_search.setBackground(new java.awt.Color(4, 71, 126));
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("Tìm");
        button_search.setToolTipText("");
        button_search.setActionCommand("");
        button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_searchMouseClicked(evt);
            }
        });
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });
        panel_button_filter.add(button_search);

        cb_filter.setBackground(new java.awt.Color(4, 71, 126));
        cb_filter.setForeground(new java.awt.Color(255, 255, 255));
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên Khách Hàng", "Số Điện Thoại", " " }));
        panel_button_filter.add(cb_filter);

        panel_thanhsearch_button.add(panel_button_filter, java.awt.BorderLayout.LINE_END);

        field_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_thanhsearch_button.add(field_search, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_thanhsearch_button, java.awt.BorderLayout.PAGE_START);

        panel_hoadon.setLayout(new java.awt.BorderLayout());

        panel_taohoadon.setBackground(new java.awt.Color(255, 255, 255));
        panel_taohoadon.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_taohoadon.setLayout(new java.awt.BorderLayout());

        panel_contain_button.setBackground(new java.awt.Color(255, 255, 255));
        panel_contain_button.setPreferredSize(new java.awt.Dimension(420, 50));
        panel_contain_button.setLayout(new java.awt.GridBagLayout());

        button_taohaodon.setText("Tạo Hóa Đơn");
        button_taohaodon.setPreferredSize(new java.awt.Dimension(120, 26));
        button_taohaodon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_taohaodonMouseClicked(evt);
            }
        });
        button_taohaodon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_taohaodonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_taohaodon, gridBagConstraints);

        jButton2.setText("jButton2");
        jButton2.setPreferredSize(new java.awt.Dimension(120, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(jButton2, gridBagConstraints);

        button_thoat.setText("Thoát");
        button_thoat.setPreferredSize(new java.awt.Dimension(120, 26));
        button_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_thoatMouseClicked(evt);
            }
        });
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });
        panel_contain_button.add(button_thoat, new java.awt.GridBagConstraints());

        panel_taohoadon.add(panel_contain_button, java.awt.BorderLayout.LINE_END);

        panel_hoadon.add(panel_taohoadon, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Tên Khách Hàng", "Số Điện Thoại", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        jPanel1.add(jPanel2);

        panel_chitiethoadon.setPreferredSize(new java.awt.Dimension(350, 470));
        panel_chitiethoadon.setLayout(new java.awt.BorderLayout());

        panel_title_chitiethoadon.setBackground(new java.awt.Color(255, 255, 255));
        panel_title_chitiethoadon.setLayout(new java.awt.BorderLayout());

        label_chitiethoadon.setBackground(new java.awt.Color(255, 255, 255));
        label_chitiethoadon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_chitiethoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_chitiethoadon.setText("Chi Tiết Hóa Đơn");
        label_chitiethoadon.setPreferredSize(new java.awt.Dimension(280, 100));
        panel_title_chitiethoadon.add(label_chitiethoadon, java.awt.BorderLayout.CENTER);

        panel_chitiethoadon.add(panel_title_chitiethoadon, java.awt.BorderLayout.PAGE_START);

        panel_thongtin_chitiethoadon.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Thuốc", "Số Lượng", "Đơn Vị", "Tổng Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        panel_thongtin_chitiethoadon.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panel_tonghoadon.setBackground(new java.awt.Color(255, 255, 255));
        panel_tonghoadon.setPreferredSize(new java.awt.Dimension(280, 200));
        panel_tonghoadon.setLayout(new java.awt.GridBagLayout());

        label_thue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_thue.setText("Thuế: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        panel_tonghoadon.add(label_thue, gridBagConstraints);

        giatrithue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giatrithue.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_tonghoadon.add(giatrithue, gridBagConstraints);

        label_tongtienhoadon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_tongtienhoadon.setText("Tổng Tiền Hóa Đơn: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        panel_tonghoadon.add(label_tongtienhoadon, gridBagConstraints);

        tongtien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tongtien.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_tonghoadon.add(tongtien, gridBagConstraints);

        panel_thongtin_chitiethoadon.add(panel_tonghoadon, java.awt.BorderLayout.PAGE_END);

        panel_chitiethoadon.add(panel_thongtin_chitiethoadon, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel_chitiethoadon);

        panel_hoadon.add(jPanel1, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_hoadon, java.awt.BorderLayout.CENTER);

        panel_main.add(panel_thongtin, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=QuanLyHoaDonGUI.MAXIMIZED_BOTH){
            this.setExtendedState(QuanLyHoaDonGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(QuanLyHoaDonGUI.NORMAL);
        }  
    }                                             

    private void button_taohaodonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void button_taohaodonMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void button_thoatMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	this.setVisible(false);
    	TongQuanGUI tongquangui = new TongQuanGUI();
    	tongquangui.setVisible(true);
    			
    }                                         

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void button_searchMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_taohaodon;
    private javax.swing.JButton button_thoat;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JTextField field_search;
    private javax.swing.JLabel giatrithue;
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel label_chitiethoadon;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_quanlyhoadon;
    private javax.swing.JLabel label_thue;
    private javax.swing.JLabel label_tongtienhoadon;
    private javax.swing.JPanel panel_button_filter;
    private javax.swing.JPanel panel_chitiethoadon;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_contain_button;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_hoadon;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_taohoadon;
    private javax.swing.JPanel panel_thanhsearch_button;
    private javax.swing.JPanel panel_thongtin;
    private javax.swing.JPanel panel_thongtin_chitiethoadon;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_title_chitiethoadon;
    private javax.swing.JPanel panel_tonghoadon;
    private javax.swing.JLabel tongtien;
    // End of variables declaration                   
}
