/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import Controller.QuanLyThuocController;


/**
 *
 * @author 44ong
 */
public class QuanLyThuocGUI extends javax.swing.JFrame {

    private Component frame;
    private QuanLyThuocController quanLyThuocControllerl;
	/**
     * Creates new form MainForm
     */
    public QuanLyThuocGUI() {
    	this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        label_quanlythuoc = new javax.swing.JLabel();
        panel_thongtin = new javax.swing.JPanel();
        panel_thanhsearch_button = new javax.swing.JPanel();
        panel_button_filter = new javax.swing.JPanel();
        button_search = new javax.swing.JButton();
        cb_filter = new javax.swing.JComboBox<>();
        field_search = new javax.swing.JTextField();
        panel_table_chucnang = new javax.swing.JPanel();
        panel_chucnang = new javax.swing.JPanel();
        panel_button_chucnang = new javax.swing.JPanel();
        button_capnhat = new javax.swing.JButton();
        button_nhapthuoc = new javax.swing.JButton();
        butotn_danhmuc = new javax.swing.JButton();
        button_thoat = new javax.swing.JButton();
        panel_table = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_main.setLayout(new java.awt.BorderLayout());

        panel_title.setBackground(new java.awt.Color(4, 71, 126));
        panel_title.setPreferredSize(new java.awt.Dimension(100, 100));
        panel_title.setLayout(new java.awt.BorderLayout());

        label_quanlythuoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlythuoc.setForeground(new java.awt.Color(255, 255, 255));
        label_quanlythuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlythuoc.setText("Quản Lý Thuốc");
        panel_title.add(label_quanlythuoc, java.awt.BorderLayout.CENTER);

        panel_main.add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_thongtin.setLayout(new java.awt.BorderLayout());

        panel_thanhsearch_button.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_thanhsearch_button.setLayout(new java.awt.BorderLayout());

        panel_button_filter.setPreferredSize(new java.awt.Dimension(200, 50));
        panel_button_filter.setLayout(new java.awt.GridLayout(1, 2));

        button_search.setBackground(new java.awt.Color(4, 71, 126));
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("Tìm");
        button_search.setToolTipText("");
        button_search.setActionCommand("");
        button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_searchMouseClicked(evt);
            }
        });
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });
        panel_button_filter.add(button_search);

        cb_filter.setBackground(new java.awt.Color(4, 71, 126));
        cb_filter.setForeground(new java.awt.Color(255, 255, 255));
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên Khách Hàng", "Số Điện Thoại", " " }));
        panel_button_filter.add(cb_filter);

        panel_thanhsearch_button.add(panel_button_filter, java.awt.BorderLayout.LINE_END);

        field_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_thanhsearch_button.add(field_search, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_thanhsearch_button, java.awt.BorderLayout.PAGE_START);

        panel_table_chucnang.setLayout(new java.awt.BorderLayout());

        panel_chucnang.setBackground(new java.awt.Color(255, 255, 255));
        panel_chucnang.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_chucnang.setLayout(new java.awt.BorderLayout());

        panel_button_chucnang.setBackground(new java.awt.Color(255, 255, 255));
        panel_button_chucnang.setPreferredSize(new java.awt.Dimension(560, 50));
        panel_button_chucnang.setLayout(new java.awt.GridBagLayout());

        button_capnhat.setText("Cập Nhật");
        button_capnhat.setPreferredSize(new java.awt.Dimension(100, 30));
        button_capnhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_capnhatMouseClicked(evt);
            }
        });
        button_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_capnhatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        panel_button_chucnang.add(button_capnhat, gridBagConstraints);

        button_nhapthuoc.setText("Nhập Thuốc");
        button_nhapthuoc.setPreferredSize(new java.awt.Dimension(100, 30));
        button_nhapthuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_themthuocMouseClicked(evt);
            }
        });
        button_nhapthuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_themthuocActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        panel_button_chucnang.add(button_nhapthuoc, gridBagConstraints);

        butotn_danhmuc.setText("Danh Mục");
        butotn_danhmuc.setPreferredSize(new java.awt.Dimension(100, 30));
        butotn_danhmuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butotn_danhmucMouseClicked(evt);
            }
        });
        butotn_danhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butotn_danhmucActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        panel_button_chucnang.add(butotn_danhmuc, gridBagConstraints);

        button_thoat.setText("Thoát");
        button_thoat.setPreferredSize(new java.awt.Dimension(100, 30));
        button_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_thoatMouseClicked(evt);
            }
        });
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });
        panel_button_chucnang.add(button_thoat, new java.awt.GridBagConstraints());

        panel_chucnang.add(panel_button_chucnang, java.awt.BorderLayout.LINE_END);

        panel_table_chucnang.add(panel_chucnang, java.awt.BorderLayout.PAGE_START);

        panel_table.setLayout(new java.awt.BorderLayout());
        
        
        
        
        
        
        
        
        // Tạo model cho bảng
        DefaultTableModel model = new DefaultTableModel() {
        /*    @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) { // Cột hình ảnh
                    return ImageIcon.class;
                }
                return Object.class;
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho phép chỉnh sửa
            }*/
        };
       
        // Thêm các cột vào model
        model.addColumn("Mã Thuốc");
        model.addColumn("Tên Thuốc");
        model.addColumn("Hình Ảnh");
        model.addColumn("Ngày Nhập");
        model.addColumn("Ngày Hết Hạn");
        model.addColumn("Số Lượng");
        model.addColumn("Đơn Vị Tính");
        model.addColumn("Đơn Giá");
        model.addColumn("Phân Loại");
        model.addColumn("Hàm Lượng");
        
        quanLyThuocControllerl = new QuanLyThuocController();
        quanLyThuocControllerl.load_data_to_table(model);

        // Tải hình ảnh từ thư mục images
        //ImageIcon[] productImages = new ImageIcon[5];
        //try {
            // Lấy hình ảnh từ package images (thư mục src/images)
            //productImages[0] = new ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"));
            //productImages[1] = new ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"));
            //productImages[2] = new ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"));
            //productImages[3] = new ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"));
            //productImages[4] = new ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"));
            
            // Resize hình ảnh nếu cần
            //for (int i = 0; i < productImages.length; i++) {
               // if (productImages[i] != null) {
                  //  Image img = productImages[i].getImage();
                  //  Image resizedImg = img.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                  //  productImages[i] = new ImageIcon(resizedImg);
               // }
           // }
       // } catch (Exception e) {
       //     JOptionPane.showMessageDialog(frame, "Không tìm thấy hình ảnh trong thư mục images", "Lỗi", JOptionPane.ERROR_MESSAGE);
        //    e.printStackTrace();
       // }

        // Thêm dữ liệu vào bảng với hình ảnh
        //model.addRow(new Object[]{productImages[0], "250400901", "Mỹ Omachi bò hầm", "Đồ khô", "24,000", ""});
        //model.addRow(new Object[]{productImages[1], "250400902", "Kẹo dynamite sôcola", "Kẹo bánh", "18,000", ""});
        //model.addRow(new Object[]{productImages[2], "250400898", "Thăng long mềm", "Thuốc lá", "8,000", ""});
        //model.addRow(new Object[]{productImages[3], "250400899", "Thuốc lá 555 nội", "Thuốc lá", "24,000", ""});
        //model.addRow(new Object[]{productImages[4], "250400900", "Pepsi chai 400ml", "Nước ngọt", "7,500", ""});

        // Tạo bảng với model
        JTable table = new JTable(model);
        
        // Thiết lập chiều cao của từng dòng để hiển thị hình ảnh
        table.setRowHeight(80);
        
        // Thiết lập kích thước các cột
        table.getColumnModel().getColumn(0).setPreferredWidth(100); // Hình ảnh
        table.getColumnModel().getColumn(1).setPreferredWidth(100); // Mã
        table.getColumnModel().getColumn(2).setPreferredWidth(200); // Tên
        table.getColumnModel().getColumn(3).setPreferredWidth(100); // Danh mục
        table.getColumnModel().getColumn(4).setPreferredWidth(100); // Giá bán
        table.getColumnModel().getColumn(5).setPreferredWidth(100);
        table.getColumnModel().getColumn(6).setPreferredWidth(100);
        table.getColumnModel().getColumn(7).setPreferredWidth(100);
        table.getColumnModel().getColumn(8).setPreferredWidth(100);// Thao tác
        table.getColumnModel().getColumn(9).setPreferredWidth(100);

        // Căn giữa nội dung các cột (trừ cột hình ảnh)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 1; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Thêm bảng vào scroll pane
        JScrollPane scrollPane = new JScrollPane(table);
        
        
        
        panel_table.add(scrollPane);
        
        
        
        
        
        
        
        panel_table_chucnang.add(panel_table, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_table_chucnang, java.awt.BorderLayout.CENTER);
        
        
        
        
        
        
        MenuForm_2 menuForm_2 = new MenuForm_2(new MenuForm_2.MenuListener() {
            
        	/*@Override public void onDrugImportSelected() { showFrame(new DrugImportFrame()); }
            @Override public void onDrugUpdateSelected() { showFrame(new DrugUpdateFrame()); }
            @Override public void onDrugListSelected() { showFrame(new DrugListFrame()); }
            @Override public void onInvoiceCreateSelected() { showFrame(new InvoiceCreateFrame()); }
            @Override public void onInvoiceListSelected() { showFrame(new InvoiceListFrame()); }
            @Override public void onRevenueStatsSelected() { showFrame(new RevenueStatsFrame()); }
            @Override public void onDrugStatsSelected() { showFrame(new DrugStatsFrame()); }
            @Override public void onStaffListSelected() { showFrame(new StaffListFrame()); }
            @Override public void onAddStaffSelected() { showFrame(new AddStaffFrame()); }
            @Override public void onCustomerListSelected() { showFrame(new CustomerListFrame()); }
            @Override public void onAddCustomerSelected() { showFrame(new AddCustomerFrame()); }
            @Override public void onSupplierListSelected() { showFrame(new SupplierListFrame()); }
            @Override public void onAddSupplierSelected() { showFrame(new AddSupplierFrame()); }*/
        	
        	
        	
        	
        	
        	@Override public void openFormNhapThuoc() { showFrame(new NhapThuocGUI()); }
            @Override public void openFormCapNhatThuoc() { showFrame(new DrugUpdateFrame()); }
            @Override public void openFormDanhSachThuoc() { showFrame(new QuanLyThuocGUI()); }
            @Override public void openFormTaoHoaDon() { showFrame(new TaoHoaDonGUI()); }
            @Override public void openFormDanhSachHoaDon() { showFrame(new QuanLyHoaDonGUI()); }
            @Override public void openFormThongKeDoanhThu() { showFrame(new ThongKeDoanhThuGUI()); }
            @Override public void openFormThongKeThuoc() { showFrame(new ThongKeThuocGUI()); }
            @Override public void openFormDanhSachNhanVien() { showFrame(new QuanLyNhanVienGUI()); }
            @Override public void openFormThemNhanVien() { showFrame(new AddStaffFrame()); }
            @Override public void openFormDanhSachKhachHang() { showFrame(new CustomerListFrame()); }
            @Override public void openFormThemKhachHang() { showFrame(new AddCustomerFrame()); }
            @Override public void openFormNhaCungCap() { showFrame(new SupplierListFrame()); }
            @Override public void openFormThemNhaCungCap() { showFrame(new AddSupplierFrame()); }
        	
        });
        
        
        
        
        
        panel_main.add(menuForm_2, java.awt.BorderLayout.WEST);
        
        
        panel_main.add(panel_thongtin, java.awt.BorderLayout.CENTER);


        getContentPane().add(panel_main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=QuanLyThuocGUI.MAXIMIZED_BOTH){
            this.setExtendedState(QuanLyThuocGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(QuanLyThuocGUI.NORMAL);
        }  
    }                                             

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void button_searchMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_capnhatActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void button_capnhatMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:

    			
    }                                           

    private void button_themthuocActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void button_themthuocMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
    	this.setVisible(false);
    	NhapThuocGUI nhapthuocgui = new NhapThuocGUI();
    	nhapthuocgui.setVisible(true);
    }                                             

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void button_thoatMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	this.setVisible(false);
    	TongQuanGUI tongquangui = new TongQuanGUI();
    	tongquangui.setVisible(true);
    }                                         

    private void butotn_danhmucActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void butotn_danhmucMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThuocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton butotn_danhmuc;
    private javax.swing.JButton button_capnhat;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_nhapthuoc;
    private javax.swing.JButton button_thoat;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JTextField field_search;
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_quanlythuoc;
    private javax.swing.JPanel panel_button_chucnang;
    private javax.swing.JPanel panel_button_filter;
    private javax.swing.JPanel panel_chucnang;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_table;
    private javax.swing.JPanel panel_table_chucnang;
    private javax.swing.JPanel panel_thanhsearch_button;
    private javax.swing.JPanel panel_thongtin;
    private javax.swing.JPanel panel_title;
    
    private QuanLyThuocController quanLyThuocController;
    
    private MenuForm_2 menuForm_2;
    // End of variables declaration       
    
    
    private void showFrame(JFrame frame) {
    	this.setVisible(false);
        frame.setVisible(true);
    }
    
    
    public void loaddata_fromdatabase() {
    	
    }
    
}
