/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 44ong
 */
public class QuanLyThuocGUI extends javax.swing.JFrame {

    private Component frame;
	/**
     * Creates new form MainForm
     */
    public QuanLyThuocGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel_left = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        label_quanlythuoc = new javax.swing.JLabel();
        panel_capnhat = new javax.swing.JPanel();
        label_capnhat = new javax.swing.JLabel();
        panel_nhapthuoc = new javax.swing.JPanel();
        label_nhapthuoc = new javax.swing.JLabel();
        panel_baocaotonkho = new javax.swing.JPanel();
        label_baocaotonkho = new javax.swing.JLabel();
        panel_hansudung = new javax.swing.JPanel();
        label_canhbaohansudung = new javax.swing.JLabel();
        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_right = new javax.swing.JPanel();
        panel_search = new javax.swing.JPanel();
        panel_filter_search = new javax.swing.JPanel();
        button_search = new javax.swing.JButton();
        cb_filter = new javax.swing.JComboBox<>();
        panel_thanh_search = new javax.swing.JPanel();
        field_timkiem = new javax.swing.JTextField();
        panel_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_left.setBackground(new java.awt.Color(225, 226, 240));
        panel_left.setPreferredSize(new java.awt.Dimension(200, 470));
        panel_left.setLayout(new java.awt.GridLayout(8, 1));

        panel_title.setBackground(new java.awt.Color(225, 226, 240));
        panel_title.setLayout(new java.awt.BorderLayout());

        label_quanlythuoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlythuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlythuoc.setText("Quản Lý Thuốc");
        panel_title.add(label_quanlythuoc, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_title);

        panel_capnhat.setBackground(new java.awt.Color(4, 71, 126));
        panel_capnhat.setLayout(new java.awt.BorderLayout());

        label_capnhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_capnhat.setForeground(new java.awt.Color(255, 255, 255));
        label_capnhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_capnhat.setText("Cập Nhật Thuốc");
        label_capnhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_capnhatMouseClicked(evt);
            }
        });
        panel_capnhat.add(label_capnhat, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_capnhat);

        panel_nhapthuoc.setBackground(new java.awt.Color(4, 71, 126));
        panel_nhapthuoc.setLayout(new java.awt.BorderLayout());

        label_nhapthuoc.setBackground(new java.awt.Color(32, 86, 161));
        label_nhapthuoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_nhapthuoc.setForeground(new java.awt.Color(255, 255, 255));
        label_nhapthuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nhapthuoc.setText("Nhập Thuốc");
        label_nhapthuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_nhapthuocMouseClicked(evt);
            }
        });
        panel_nhapthuoc.add(label_nhapthuoc, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_nhapthuoc);

        panel_baocaotonkho.setBackground(new java.awt.Color(4, 71, 126));
        panel_baocaotonkho.setLayout(new java.awt.BorderLayout());

        label_baocaotonkho.setBackground(new java.awt.Color(32, 86, 161));
        label_baocaotonkho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_baocaotonkho.setForeground(new java.awt.Color(255, 255, 255));
        label_baocaotonkho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_baocaotonkho.setText("Báo Cáo Tồn Kho");
        panel_baocaotonkho.add(label_baocaotonkho, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_baocaotonkho);

        panel_hansudung.setBackground(new java.awt.Color(4, 71, 126));
        panel_hansudung.setLayout(new java.awt.BorderLayout());

        label_canhbaohansudung.setBackground(new java.awt.Color(32, 86, 161));
        label_canhbaohansudung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_canhbaohansudung.setForeground(new java.awt.Color(255, 255, 255));
        label_canhbaohansudung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_canhbaohansudung.setText("Cảnh Báo Hạn Sử Dụng");
        panel_hansudung.add(label_canhbaohansudung, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_hansudung);

        getContentPane().add(panel_left, java.awt.BorderLayout.LINE_START);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_right.setForeground(new java.awt.Color(255, 255, 255));
        panel_right.setPreferredSize(new java.awt.Dimension(700, 470));
        panel_right.setLayout(new java.awt.BorderLayout());

        panel_search.setPreferredSize(new java.awt.Dimension(700, 50));
        panel_search.setLayout(new java.awt.BorderLayout());

        panel_filter_search.setPreferredSize(new java.awt.Dimension(200, 50));
        panel_filter_search.setLayout(new java.awt.GridLayout(1, 2));

        button_search.setBackground(new java.awt.Color(4, 71, 126));
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("Tìm");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });
        panel_filter_search.add(button_search);

        cb_filter.setBackground(new java.awt.Color(4, 71, 126));
        cb_filter.setForeground(new java.awt.Color(255, 255, 255));
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên", "Nhóm Thuốc" }));
        panel_filter_search.add(cb_filter);

        panel_search.add(panel_filter_search, java.awt.BorderLayout.LINE_END);

        panel_thanh_search.setLayout(new java.awt.BorderLayout());

        field_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_thanh_search.add(field_timkiem, java.awt.BorderLayout.CENTER);

        panel_search.add(panel_thanh_search, java.awt.BorderLayout.CENTER);

        panel_right.add(panel_search, java.awt.BorderLayout.PAGE_START);

        panel_main.setLayout(new java.awt.GridLayout(2, 1));
        
        
        
        
        
        
        
        // Tạo model cho bảng
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) { // Cột hình ảnh
                    return ImageIcon.class;
                }
                return Object.class;
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho phép chỉnh sửa
            }
        };

        // Thêm các cột vào model
        model.addColumn("Hình ảnh");
        model.addColumn("Mã");
        model.addColumn("Tên");
        model.addColumn("Danh mục");
        model.addColumn("Giá bán");
        model.addColumn("Thao tác");

        // Tải hình ảnh từ thư mục images
        ImageIcon[] productImages = new ImageIcon[5];
        try {
            // Lấy hình ảnh từ package images (thư mục src/images)
            productImages[0] = new ImageIcon(ProductTableWithImages.class.getResource("/Image/fullscreen-removebg-preview (1).png"));
            productImages[1] = new ImageIcon(ProductTableWithImages.class.getResource("/Image/fullscreen-removebg-preview (1).png"));
            productImages[2] = new ImageIcon(ProductTableWithImages.class.getResource("/Image/fullscreen-removebg-preview (1).png"));
            productImages[3] = new ImageIcon(ProductTableWithImages.class.getResource("/Image/fullscreen-removebg-preview (1).png"));
            productImages[4] = new ImageIcon(ProductTableWithImages.class.getResource("/Image/fullscreen-removebg-preview (1).png"));
            
            // Resize hình ảnh nếu cần
            for (int i = 0; i < productImages.length; i++) {
                if (productImages[i] != null) {
                    Image img = productImages[i].getImage();
                    Image resizedImg = img.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                    productImages[i] = new ImageIcon(resizedImg);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame, "Không tìm thấy hình ảnh trong thư mục images", "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // Thêm dữ liệu vào bảng với hình ảnh
        model.addRow(new Object[]{productImages[0], "250400901", "Mỹ Omachi bò hầm", "Đồ khô", "24,000", ""});
        model.addRow(new Object[]{productImages[1], "250400902", "Kẹo dynamite sôcola", "Kẹo bánh", "18,000", ""});
        model.addRow(new Object[]{productImages[2], "250400898", "Thăng long mềm", "Thuốc lá", "8,000", ""});
        model.addRow(new Object[]{productImages[3], "250400899", "Thuốc lá 555 nội", "Thuốc lá", "24,000", ""});
        model.addRow(new Object[]{productImages[4], "250400900", "Pepsi chai 400ml", "Nước ngọt", "7,500", ""});

        // Tạo bảng với model
        JTable table = new JTable(model);
        
        // Thiết lập chiều cao của từng dòng để hiển thị hình ảnh
        table.setRowHeight(80);
        
        // Thiết lập kích thước các cột
        table.getColumnModel().getColumn(0).setPreferredWidth(100); // Hình ảnh
        table.getColumnModel().getColumn(1).setPreferredWidth(100); // Mã
        table.getColumnModel().getColumn(2).setPreferredWidth(200); // Tên
        table.getColumnModel().getColumn(3).setPreferredWidth(100); // Danh mục
        table.getColumnModel().getColumn(4).setPreferredWidth(100); // Giá bán
        table.getColumnModel().getColumn(5).setPreferredWidth(100); // Thao tác

        // Căn giữa nội dung các cột (trừ cột hình ảnh)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 1; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Thêm bảng vào scroll pane
        JScrollPane scrollPane = new JScrollPane(table);
        
        
        
        panel_main.add(scrollPane);
        
        
        
        
        
        panel_right.add(panel_main, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_right, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=QuanLyThuocGUI.MAXIMIZED_BOTH){
            this.setExtendedState(QuanLyThuocGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(QuanLyThuocGUI.NORMAL);
        }  
    }                                             

    private void label_capnhatMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void label_nhapthuocMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
    }                                            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuocGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThuocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button_search;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JTextField field_timkiem;
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JLabel label_baocaotonkho;
    private javax.swing.JLabel label_canhbaohansudung;
    private javax.swing.JLabel label_capnhat;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_nhapthuoc;
    private javax.swing.JLabel label_quanlythuoc;
    private javax.swing.JPanel panel_baocaotonkho;
    private javax.swing.JPanel panel_capnhat;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_filter_search;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_hansudung;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_nhapthuoc;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel panel_search;
    private javax.swing.JPanel panel_thanh_search;
    private javax.swing.JPanel panel_title;
    // End of variables declaration                   
}
