/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Iterator;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import Controller.QuanLyThuocController;
import Models.Thuoc;


/**
 *
 * @author 44ong
 */
public class TaoHoaDonGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public TaoHoaDonGUI() {
    	this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        label_quanlyhoadon = new javax.swing.JLabel();
        panel_thongtin = new javax.swing.JPanel();
        panel_thanhsearch_button = new javax.swing.JPanel();
        panel_button_filter = new javax.swing.JPanel();
        button_search = new javax.swing.JButton();
        cb_filter = new javax.swing.JComboBox<>();
        field_search = new javax.swing.JTextField();
        panel_hoadon = new javax.swing.JPanel();
        panel_taohoadon = new javax.swing.JPanel();
        panel_contain_button = new javax.swing.JPanel();
        button_them = new javax.swing.JButton();
        button_xoa = new javax.swing.JButton();
        button_hoantac = new javax.swing.JButton();
        cb_soluong = new javax.swing.JComboBox<>();
        button_quaylai = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panel_chitiethoadon = new javax.swing.JPanel();
        panel_table_thongtinthuoc = new javax.swing.JPanel();
        panel_sanpham = new javax.swing.JPanel();
        panel_thongtinsanpham = new javax.swing.JPanel();
        label_mathuoc = new javax.swing.JLabel();
        giatri_mathuoc = new javax.swing.JLabel();
        label_tenthuoc = new javax.swing.JLabel();
        giatri_tenthuoc = new javax.swing.JLabel();
        label_hamhuong = new javax.swing.JLabel();
        giatri_hamluong = new javax.swing.JLabel();
        label_phanloai = new javax.swing.JLabel();
        giatri_phanloai = new javax.swing.JLabel();
        label_giatien = new javax.swing.JLabel();
        giatri_giatien = new javax.swing.JLabel();
        label_donvi = new javax.swing.JLabel();
        giatri_donvi = new javax.swing.JLabel();
        laebl_thanhphanchinh = new javax.swing.JLabel();
        giatri_thanhphanchinh = new javax.swing.JLabel();
        label_ngayhethan = new javax.swing.JLabel();
        giatri_ngayhethan = new javax.swing.JLabel();
        panel_hinhanhsanpham = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_thongtin1 = new javax.swing.JPanel();
        label_tenkhachhang = new javax.swing.JLabel();
        field_tenkhachhang = new javax.swing.JTextField();
        label_sdt = new javax.swing.JLabel();
        field_sdt = new javax.swing.JTextField();
        label_diachi = new javax.swing.JLabel();
        field_diachi = new javax.swing.JTextField();
        label_tennhanvien = new javax.swing.JLabel();
        field_tennhanvien = new javax.swing.JTextField();
        label_ngayban = new javax.swing.JLabel();
        field_ngayban = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        panel_table_thuoc_hoadon = new javax.swing.JPanel();
        scroll_thuoc_hoadon = new javax.swing.JScrollPane();
        table_thuoc_hoadon = new javax.swing.JTable();
        panel_table_listthuoc = new JPanel();
        table_listthuoc = new javax.swing.JTable();
        
       
        
        scroll_panel_listthuoc = new javax.swing.JScrollPane();
        
        quanLyThuocController = new QuanLyThuocController();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_main.setLayout(new java.awt.BorderLayout());

        panel_title.setBackground(new java.awt.Color(4, 71, 126));
        panel_title.setPreferredSize(new java.awt.Dimension(100, 100));
        panel_title.setLayout(new java.awt.BorderLayout());

        label_quanlyhoadon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlyhoadon.setForeground(new java.awt.Color(255, 255, 255));
        label_quanlyhoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlyhoadon.setText("Quản Lý Hóa Đơn");
        panel_title.add(label_quanlyhoadon, java.awt.BorderLayout.CENTER);

        panel_main.add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_thongtin.setLayout(new java.awt.BorderLayout());

        panel_thanhsearch_button.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_thanhsearch_button.setLayout(new java.awt.BorderLayout());

        panel_button_filter.setPreferredSize(new java.awt.Dimension(200, 50));
        panel_button_filter.setLayout(new java.awt.GridLayout(1, 2));

        button_search.setBackground(new java.awt.Color(4, 71, 126));
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("Tìm");
        button_search.setToolTipText("");
        button_search.setActionCommand("");
        button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_searchMouseClicked(evt);
            }
        });
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });
        panel_button_filter.add(button_search);

        cb_filter.setBackground(new java.awt.Color(4, 71, 126));
        cb_filter.setForeground(new java.awt.Color(255, 255, 255));
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên", "Chức Năng", "Thành Phần" }));
        panel_button_filter.add(cb_filter);

        panel_thanhsearch_button.add(panel_button_filter, java.awt.BorderLayout.LINE_END);

        field_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_thanhsearch_button.add(field_search, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_thanhsearch_button, java.awt.BorderLayout.PAGE_START);

        panel_hoadon.setLayout(new java.awt.BorderLayout());

        panel_taohoadon.setBackground(new java.awt.Color(255, 255, 255));
        panel_taohoadon.setPreferredSize(new java.awt.Dimension(900, 50));
        panel_taohoadon.setLayout(new java.awt.BorderLayout());

        panel_contain_button.setBackground(new java.awt.Color(255, 255, 255));
        panel_contain_button.setPreferredSize(new java.awt.Dimension(470, 50));
        panel_contain_button.setLayout(new java.awt.GridBagLayout());

        button_them.setText("Thêm ");
        button_them.setActionCommand("Thêm");
        button_them.setPreferredSize(new java.awt.Dimension(120, 26));
        button_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_themMouseClicked(evt);
            }
        });
        button_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_themActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_them, gridBagConstraints);

        button_xoa.setText("Xóa");
        button_xoa.setPreferredSize(new java.awt.Dimension(120, 26));
        button_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_xoaMouseClicked(evt);
            }
        });
        button_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_xoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_xoa, gridBagConstraints);

        button_hoantac.setText("Hoàn Tác");
        button_hoantac.setPreferredSize(new java.awt.Dimension(120, 26));
        button_hoantac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_hoantacMouseClicked(evt);
            }
        });
        button_hoantac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hoantacActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(button_hoantac, gridBagConstraints);

        cb_soluong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        panel_contain_button.add(cb_soluong, gridBagConstraints);

        button_quaylai.setText("Thoát");
        button_quaylai.setPreferredSize(new java.awt.Dimension(120, 26));
        button_quaylai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_quaylaiMouseClicked(evt);
            }
        });
        button_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_quaylaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        panel_contain_button.add(button_quaylai, gridBagConstraints);

        panel_taohoadon.add(panel_contain_button, java.awt.BorderLayout.LINE_END);

        panel_hoadon.add(panel_taohoadon, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        panel_chitiethoadon.setPreferredSize(new java.awt.Dimension(350, 470));
        panel_chitiethoadon.setLayout(new java.awt.BorderLayout());

        panel_table_thongtinthuoc.setLayout(new java.awt.GridLayout(1, 2));
        
        

        panel_sanpham.setLayout(new java.awt.GridLayout(3, 1)); // edit this line
        
        String[] colname = {"Mã Thuốc", "Tên Thuốc", "Thành Phần Chính", "Hàm Lượng"};
        Object[][] rawdata = {
        		{null,null,null,null},
        		{null,null,null,null},
        		{null,null,null,null}
        };
        
        tablemodel_thuoc_search = new DefaultTableModel(rawdata, colname);
        
        table_listthuoc.setModel(tablemodel_thuoc_search);
        scroll_panel_listthuoc.setViewportView(table_listthuoc);
        
        table_listthuoc.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int row  = table_listthuoc.rowAtPoint(e.getPoint());
        		//int col = table_listthuoc.columnAtPoint(e.getPoint());
        		
        		if(row>=0) {
        			String mathuoc = (String) table_listthuoc.getValueAt(row, 0);
        			Thuoc thuoc = quanLyThuocController.timThuocbyField("maThuoc", mathuoc);
        			giatri_mathuoc.setText(thuoc.getMaThuoc());
        			giatri_donvi.setText(thuoc.getDonViTinh());
        			giatri_giatien.setText(Double.toString(thuoc.getdonGia()));
        			giatri_ngayhethan.setText(thuoc.getNgayHetHan().toString());
        			giatri_phanloai.setText(thuoc.getPhanLoai());
        			giatri_hamluong.setText(Double.toString(thuoc.getHamLuong()));
        			giatri_thanhphanchinh.setText("Null");
        			giatri_tenthuoc.setText(thuoc.getTenThuoc());
        			
        		}
        	
        	}
		});
        panel_sanpham.add(scroll_panel_listthuoc);
        
        
        panel_thongtinsanpham.setBackground(new java.awt.Color(255, 255, 255));
        panel_thongtinsanpham.setLayout(new java.awt.GridBagLayout());

        label_mathuoc.setText("Mã Thuốc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(label_mathuoc, gridBagConstraints);

        giatri_mathuoc.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_mathuoc, gridBagConstraints);

        label_tenthuoc.setText("Tên Thuốc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(label_tenthuoc, gridBagConstraints);

        giatri_tenthuoc.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_tenthuoc, gridBagConstraints);

        label_hamhuong.setText("Hàm Lượng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(label_hamhuong, gridBagConstraints);

        giatri_hamluong.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_hamluong, gridBagConstraints);

        label_phanloai.setText("Phân Loại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(label_phanloai, gridBagConstraints);

        giatri_phanloai.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_phanloai, gridBagConstraints);

        label_giatien.setText("Giá TIền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(label_giatien, gridBagConstraints);

        giatri_giatien.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_giatien, gridBagConstraints);

        label_donvi.setText("Đơn Vị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(label_donvi, gridBagConstraints);

        giatri_donvi.setText("jLabel15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_donvi, gridBagConstraints);

        laebl_thanhphanchinh.setText("Thành Phần Chính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        panel_thongtinsanpham.add(laebl_thanhphanchinh, gridBagConstraints);

        giatri_thanhphanchinh.setText("jLabel17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_thanhphanchinh, gridBagConstraints);

        label_ngayhethan.setText("Ngày Hết Hạn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        panel_thongtinsanpham.add(label_ngayhethan, gridBagConstraints);

        giatri_ngayhethan.setText("jLabel20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panel_thongtinsanpham.add(giatri_ngayhethan, gridBagConstraints);

        panel_sanpham.add(panel_thongtinsanpham);

        panel_hinhanhsanpham.setBackground(new java.awt.Color(255, 255, 255));
        panel_hinhanhsanpham.setLayout(new java.awt.BorderLayout());

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Picture1.png"))); // NOI18N
        panel_hinhanhsanpham.add(jLabel18, java.awt.BorderLayout.CENTER);

        panel_sanpham.add(panel_hinhanhsanpham);
        
        
        

        panel_table_thongtinthuoc.add(panel_sanpham);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        panel_thongtin1.setBackground(new java.awt.Color(255, 255, 255));
        panel_thongtin1.setLayout(new java.awt.GridBagLayout());

        label_tenkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_tenkhachhang.setText("Tên Khách Hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(label_tenkhachhang, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(field_tenkhachhang, gridBagConstraints);

        label_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_sdt.setText("Số Điện Thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(label_sdt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(field_sdt, gridBagConstraints);

        label_diachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_diachi.setText("Địa Chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(label_diachi, gridBagConstraints);

        field_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_diachiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(field_diachi, gridBagConstraints);

        label_tennhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_tennhanvien.setText("Tên Nhân Viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(label_tennhanvien, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(field_tennhanvien, gridBagConstraints);

        label_ngayban.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_ngayban.setText("Ngày Bán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(label_ngayban, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(field_ngayban, gridBagConstraints);

        jLabel6.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panel_thongtin1.add(jTextField6, gridBagConstraints);

        jPanel2.add(panel_thongtin1);

        
        
        
        
        panel_table_thuoc_hoadon.setLayout(new java.awt.BorderLayout());
        
        
        
        String[] col = {"Mã Thuốc", "Tên Thuốc", "Số Lượng", "Giá"};
        
        Object[][] data = {
        		
        		{null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
        		
        };
        DefaultTableModel  model_thuoc_hoadon = new DefaultTableModel(data,col);
        
        table_thuoc_hoadon.setModel(model_thuoc_hoadon);
        
        
        scroll_thuoc_hoadon.setViewportView(table_thuoc_hoadon);
        panel_table_thuoc_hoadon.add(scroll_thuoc_hoadon, java.awt.BorderLayout.CENTER);
        jPanel2.add(panel_table_thuoc_hoadon);
        /*table_thuoc_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Thuốc", "Tên Thuốc", "Số Lượng", "Giá"
            }
        ));
        scroll_thuoc_hoadon.setViewportView(table_thuoc_hoadon);

        panel_table_thuoc_hoadon.add(scroll_thuoc_hoadon, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_table_thuoc_hoadon);*/
        
        
        
        
        

        panel_table_thongtinthuoc.add(jPanel2);

        panel_chitiethoadon.add(panel_table_thongtinthuoc, java.awt.BorderLayout.CENTER);

        jPanel1.add(panel_chitiethoadon);

        panel_hoadon.add(jPanel1, java.awt.BorderLayout.CENTER);

        panel_thongtin.add(panel_hoadon, java.awt.BorderLayout.CENTER);
        
        
        
        
        
        
        
        MenuForm_2 menuForm_2 = new MenuForm_2(new MenuForm_2.MenuListener() {
            
        	/*@Override public void onDrugImportSelected() { showFrame(new DrugImportFrame()); }
            @Override public void onDrugUpdateSelected() { showFrame(new DrugUpdateFrame()); }
            @Override public void onDrugListSelected() { showFrame(new DrugListFrame()); }
            @Override public void onInvoiceCreateSelected() { showFrame(new InvoiceCreateFrame()); }
            @Override public void onInvoiceListSelected() { showFrame(new InvoiceListFrame()); }
            @Override public void onRevenueStatsSelected() { showFrame(new RevenueStatsFrame()); }
            @Override public void onDrugStatsSelected() { showFrame(new DrugStatsFrame()); }
            @Override public void onStaffListSelected() { showFrame(new StaffListFrame()); }
            @Override public void onAddStaffSelected() { showFrame(new AddStaffFrame()); }
            @Override public void onCustomerListSelected() { showFrame(new CustomerListFrame()); }
            @Override public void onAddCustomerSelected() { showFrame(new AddCustomerFrame()); }
            @Override public void onSupplierListSelected() { showFrame(new SupplierListFrame()); }
            @Override public void onAddSupplierSelected() { showFrame(new AddSupplierFrame()); }*/
        	
        	
        	
        	
        	
        	@Override public void openFormNhapThuoc() { showFrame(new NhapThuocGUI()); }
            @Override public void openFormCapNhatThuoc() { showFrame(new DrugUpdateFrame()); }
            @Override public void openFormDanhSachThuoc() { showFrame(new QuanLyThuocGUI()); }
            @Override public void openFormTaoHoaDon() { showFrame(new TaoHoaDonGUI()); }
            @Override public void openFormDanhSachHoaDon() { showFrame(new QuanLyHoaDonGUI()); }
            @Override public void openFormThongKeDoanhThu() { showFrame(new ThongKeDoanhThuGUI()); }
            @Override public void openFormThongKeThuoc() { showFrame(new ThongKeThuocGUI()); }
            @Override public void openFormDanhSachNhanVien() { showFrame(new QuanLyNhanVienGUI()); }
            @Override public void openFormThemNhanVien() { showFrame(new AddStaffFrame()); }
            @Override public void openFormDanhSachKhachHang() { showFrame(new CustomerListFrame()); }
            @Override public void openFormThemKhachHang() { showFrame(new AddCustomerFrame()); }
            @Override public void openFormNhaCungCap() { showFrame(new SupplierListFrame()); }
            @Override public void openFormThemNhaCungCap() { showFrame(new AddSupplierFrame()); }
        	
        });
        
        
        
        
        
        panel_main.add(menuForm_2, java.awt.BorderLayout.WEST);
        

        panel_main.add(panel_thongtin, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=TaoHoaDonGUI.MAXIMIZED_BOTH){
            this.setExtendedState(TaoHoaDonGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(TaoHoaDonGUI.NORMAL);
        }  
    }                                             

    private void field_diachiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	
    	tablemodel_thuoc_search.setRowCount(0);
    	
    	quanLyThuocController =new  QuanLyThuocController();
    	if(cb_filter.getSelectedIndex()==0) {
    		String tenColDB = "tenThuoc";
    		String tenThuoc = field_search.getText();
    		List<Thuoc> listthuoc =  quanLyThuocController.timListThuocbyField(tenColDB,tenThuoc);
    		for(Thuoc thuoc: listthuoc) {
    			Object[] data = {thuoc.getMaThuoc(), thuoc.getTenThuoc(), null, thuoc.getHamLuong()};
    			tablemodel_thuoc_search.addRow(data);
    		}
    		
    	}
    	if(cb_filter.getSelectedIndex()==1) {
    		String tenColDB = "phanLoai";
    		String phanloai = field_search.getText();
    		
    		List<Thuoc> listthuoc =  quanLyThuocController.timListThuocbyField(tenColDB,phanloai);
    		for(Thuoc thuoc: listthuoc) {
    			Object[] data = {thuoc.getMaThuoc(), thuoc.getTenThuoc(), null, thuoc.getHamLuong()};
    			tablemodel_thuoc_search.addRow(data);
    		}
    		
    	}
    	
    	
    }                                             

    private void button_searchMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_themActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void button_themMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
    	
    	
    }                                             

    private void button_xoaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void button_xoaMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void button_hoantacActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void button_hoantacMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void button_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	this.setVisible(false);
    	QuanLyHoaDonGUI quanlyhoadongui = new QuanLyHoaDonGUI();
    	quanlyhoadongui.setVisible(true);
    }                                              

    private void button_quaylaiMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoHoaDonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button_hoantac;
    private javax.swing.JButton button_quaylai;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_them;
    private javax.swing.JButton button_xoa;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JComboBox<String> cb_soluong;
    private javax.swing.JTextField field_diachi;
    private javax.swing.JTextField field_ngayban;
    private javax.swing.JTextField field_sdt;
    private javax.swing.JTextField field_search;
    private javax.swing.JTextField field_tenkhachhang;
    private javax.swing.JTextField field_tennhanvien;
    private javax.swing.JLabel giatri_donvi;
    private javax.swing.JLabel giatri_giatien;
    private javax.swing.JLabel giatri_hamluong;
    private javax.swing.JLabel giatri_mathuoc;
    private javax.swing.JLabel giatri_ngayhethan;
    private javax.swing.JLabel giatri_phanloai;
    private javax.swing.JLabel giatri_tenthuoc;
    private javax.swing.JLabel giatri_thanhphanchinh;
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scroll_thuoc_hoadon;
    private javax.swing.JTable table_thuoc_hoadon;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_diachi;
    private javax.swing.JLabel label_donvi;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_giatien;
    private javax.swing.JLabel label_hamhuong;
    private javax.swing.JLabel label_mathuoc;
    private javax.swing.JLabel label_ngayban;
    private javax.swing.JLabel label_ngayhethan;
    private javax.swing.JLabel label_phanloai;
    private javax.swing.JLabel label_quanlyhoadon;
    private javax.swing.JLabel label_sdt;
    private javax.swing.JLabel label_tenkhachhang;
    private javax.swing.JLabel label_tennhanvien;
    private javax.swing.JLabel label_tenthuoc;
    private javax.swing.JLabel laebl_thanhphanchinh;
    private javax.swing.JPanel panel_button_filter;
    private javax.swing.JPanel panel_chitiethoadon;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_contain_button;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_hinhanhsanpham;
    private javax.swing.JPanel panel_hoadon;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_sanpham;
    private javax.swing.JPanel panel_table_thuoc_hoadon;
    private javax.swing.JPanel panel_table_thongtinthuoc;
    private javax.swing.JPanel panel_taohoadon;
    private javax.swing.JPanel panel_thanhsearch_button;
    private javax.swing.JPanel panel_thongtin;
    private javax.swing.JPanel panel_thongtin1;
    private javax.swing.JPanel panel_thongtinsanpham;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_table_listthuoc;
    private javax.swing.JTable table_listthuoc;
    private javax.swing.JScrollPane scroll_panel_listthuoc;
    private DefaultTableModel tablemodel_thuoc_search;
    
    private QuanLyThuocController quanLyThuocController;
    
    // End of variables declaration    
    
    private void showFrame(JFrame frame) {
    	this.setVisible(false);
        frame.setVisible(true);
    }
}
