/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;

import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.jfree.chart.ChartPanel;

/**
 *
 * @author 44ong
 */
public class TongQuanGUI extends javax.swing.JFrame {

    private JLabel label_thongke;
	/**
     * Creates new form MainForm
     */
    public TongQuanGUI() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panel_header = new javax.swing.JPanel();
        icon_close_fullscreen = new javax.swing.JPanel();
        panel_fullscreen = new javax.swing.JPanel();
        label_fullscreen = new javax.swing.JLabel();
        panel_close = new javax.swing.JPanel();
        label_close = new javax.swing.JLabel();
        panel_left = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_tongquan = new javax.swing.JPanel();
        label_tongquan = new javax.swing.JLabel();
        panel_quanlythuoc = new javax.swing.JPanel();
        label_quanlythuoc = new javax.swing.JLabel();
        panel_quanlyhoadon = new javax.swing.JPanel();
        label_quanlyhoadon = new javax.swing.JLabel();
        panel_thongke = new javax.swing.JPanel();
        label_thongke = new javax.swing.JLabel();
        panel_right = new javax.swing.JPanel();
        panel_right_top = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        panel_thongso = new javax.swing.JPanel();
        panel_right_bot = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_header.setBackground(new java.awt.Color(204, 204, 204));
        panel_header.setPreferredSize(new java.awt.Dimension(900, 30));
        panel_header.setLayout(new java.awt.BorderLayout());

        icon_close_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        icon_close_fullscreen.setPreferredSize(new java.awt.Dimension(60, 30));
        icon_close_fullscreen.setLayout(new javax.swing.BoxLayout(icon_close_fullscreen, javax.swing.BoxLayout.X_AXIS));

        panel_fullscreen.setBackground(new java.awt.Color(204, 204, 204));
        panel_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen-removebg-preview (1).png"))); // NOI18N
        label_fullscreen.setText("jLabel2");
        label_fullscreen.setPreferredSize(new java.awt.Dimension(30, 30));
        label_fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fullscreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fullscreenLayout = new javax.swing.GroupLayout(panel_fullscreen);
        panel_fullscreen.setLayout(panel_fullscreenLayout);
        panel_fullscreenLayout.setHorizontalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullscreenLayout.createSequentialGroup()
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fullscreenLayout.setVerticalGroup(
            panel_fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fullscreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_fullscreen);

        panel_close.setBackground(new java.awt.Color(204, 204, 204));
        panel_close.setPreferredSize(new java.awt.Dimension(30, 30));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clsoe-removebg-preview (1).png"))); // NOI18N
        label_close.setText("jLabel1");
        label_close.setPreferredSize(new java.awt.Dimension(30, 30));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_closeLayout = new javax.swing.GroupLayout(panel_close);
        panel_close.setLayout(panel_closeLayout);
        panel_closeLayout.setHorizontalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_closeLayout.setVerticalGroup(
            panel_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon_close_fullscreen.add(panel_close);

        panel_header.add(icon_close_fullscreen, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_header, java.awt.BorderLayout.PAGE_START);

        panel_left.setPreferredSize(new java.awt.Dimension(200, 470));
        panel_left.setLayout(new java.awt.GridLayout(5, 1));

        panel_logo.setBackground(new java.awt.Color(4, 71, 126));
        panel_logo.setLayout(new java.awt.BorderLayout());

        label_logo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_logo.setForeground(new java.awt.Color(255, 255, 255));
        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setText("logo");
        panel_logo.add(label_logo, java.awt.BorderLayout.CENTER);

        panel_left.add(panel_logo);

        panel_tongquan.setBackground(new java.awt.Color(4, 71, 126));
        panel_tongquan.setLayout(new java.awt.BorderLayout());

        label_tongquan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_tongquan.setForeground(new java.awt.Color(255, 255, 255));
        label_tongquan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tongquan.setText("Tổng Quan");
        panel_tongquan.add(label_tongquan, java.awt.BorderLayout.CENTER);
        label_tongquan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_tongquanMouseClicked(evt);
            }
        });

        panel_left.add(panel_tongquan);

        panel_quanlythuoc.setBackground(new java.awt.Color(4, 71, 126));
        panel_quanlythuoc.setLayout(new java.awt.BorderLayout());

        label_quanlythuoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlythuoc.setForeground(new java.awt.Color(255, 255, 255));
        label_quanlythuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlythuoc.setText("Quản Lý Thuốc");
        panel_quanlythuoc.add(label_quanlythuoc, java.awt.BorderLayout.CENTER);
        label_quanlythuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_quanlythuocMouseClicked(evt);
            }
        });

        panel_left.add(panel_quanlythuoc);

        panel_quanlyhoadon.setBackground(new java.awt.Color(4, 71, 126));
        panel_quanlyhoadon.setLayout(new java.awt.BorderLayout());

        label_quanlyhoadon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_quanlyhoadon.setForeground(new java.awt.Color(255, 255, 255));
        label_quanlyhoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quanlyhoadon.setText("Quản Lý Hóa Đơn");
        panel_quanlyhoadon.add(label_quanlyhoadon, java.awt.BorderLayout.CENTER);
        label_quanlyhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_quanlyhoadonMouseClicked(evt);
            }
        });
        
        

        panel_left.add(panel_quanlyhoadon);

        panel_thongke.setBackground(new java.awt.Color(4, 71, 126));
        panel_thongke.setLayout(new java.awt.BorderLayout());

        label_thongke.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_thongke.setForeground(new java.awt.Color(255, 255, 255));
        label_thongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_thongke.setText("Thống Kê");
        panel_thongke.add(label_thongke, java.awt.BorderLayout.CENTER);

        label_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
              label_thongkeMouseClicked(evt);
            }
        });
        panel_left.add(panel_thongke);

        getContentPane().add(panel_left, java.awt.BorderLayout.LINE_START);

        panel_right.setLayout(new java.awt.GridLayout(2, 1));

        panel_right_top.setBackground(new java.awt.Color(255, 255, 255));
        panel_right_top.setLayout(new java.awt.BorderLayout());

        panel_title.setBackground(new java.awt.Color(255, 255, 255));
        panel_title.setLayout(new java.awt.BorderLayout());

        label_title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("Tổng Quan Thống Kê Cơ Bản");
        panel_title.add(label_title, java.awt.BorderLayout.CENTER);

        panel_right_top.add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_thongso.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_thongsoLayout = new javax.swing.GroupLayout(panel_thongso);
        panel_thongso.setLayout(panel_thongsoLayout);
        panel_thongsoLayout.setHorizontalGroup(
            panel_thongsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panel_thongsoLayout.setVerticalGroup(
            panel_thongsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        
        // Chổ Quan Trọng
        panel_thongso.setPreferredSize(new java.awt.Dimension(100, 100));
        panel_thongso.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 60));
        
        DashboardPanel panel1 = new DashboardPanel(
                "Tổng Sản Phẩm", 
                "$3388880", 
                "average key 50%", 
                new Color(100, 150, 255),  // Light blue (top)
                new Color(0, 50, 150),     // Dark blue (bottom)
                true                       // 3D effect enabled
            );
        panel1.setPreferredSize(new Dimension(200,200));
        
        DashboardPanel panel2 = new DashboardPanel(
                "Doanh Thu Tháng", 
                "$338880", 
                "template file 21%", 
                new Color(150, 255, 150), // Light green
                new Color(0, 150, 0),     // Dark green
                true
            );
        panel2.setPreferredSize(new Dimension(200,200));
        
        DashboardPanel panel3 = new DashboardPanel(
                "Doanh Thu Ngày", 
                "$1281000", 
                "average key 10%", 
                new Color(220, 150, 255),  // Light purple
                new Color(100, 0, 150),    // Dark purple
                true
            );
        
        panel3.setPreferredSize(new Dimension(200,200));
        
        DashboardPanel panel4 = new DashboardPanel(
                "Doanh Thu Ngày", 
                "$1281000", 
                "average key 10%", 
                new Color(220, 150, 255),  // Light purple
                new Color(100, 0, 150),    // Dark purple
                true
            );
        
        panel4.setPreferredSize(new Dimension(200,200));
        
        DashboardPanel panel5 = new DashboardPanel(
                "Doanh Thu Tháng", 
                "$338880", 
                "template file 21%", 
                new Color(150, 255, 150), // Light green
                new Color(0, 150, 0),     // Dark green
                true
            );
        panel5.setPreferredSize(new Dimension(200,200));
        
        panel_thongso.add(panel1);
        panel_thongso.add(panel2);
        panel_thongso.add(panel3);
        panel_thongso.add(panel4);
        panel_thongso.add(panel5);

        panel_right_top.add(panel_thongso, java.awt.BorderLayout.CENTER);

        panel_right.add(panel_right_top);

        // Chổ Quan Trọng
        
        javax.swing.GroupLayout panel_right_botLayout = new javax.swing.GroupLayout(panel_right_bot);
        panel_right_bot.setLayout(panel_right_botLayout);
        panel_right_botLayout.setHorizontalGroup(
            panel_right_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panel_right_botLayout.setVerticalGroup(
            panel_right_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        
        // ve bieu do
        ChartPanel chartPanel = LineChart.createSampleChartPanel();
         
         panel_right.add(chartPanel);

         getContentPane().add(panel_right, java.awt.BorderLayout.LINE_END);

         setSize(new java.awt.Dimension(900, 500));
         setLocationRelativeTo(null);;

        getContentPane().add(panel_right, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
        
        // Chổ Quan trọng
    }// </editor-fold>                        
    
    // chinh sua nut close
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        changecolor(panel_close, new Color(245, 66, 105));
    }                                        

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        changecolor(panel_close, new Color(204,204,204));
    }                                       
    // ket thuc chinh sua nut close
    
    private void label_fullscreenMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        if(this.getExtendedState()!=TongQuanGUI.MAXIMIZED_BOTH){
            this.setExtendedState(TongQuanGUI.MAXIMIZED_BOTH);
        }else{
           this.setExtendedState(TongQuanGUI.NORMAL);
        }  
    }     
    
    private void label_tongquanMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void label_quanlythuocMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
    	this.setVisible(false);
    	QuanLyThuocGUI quanlythuocgui =  new QuanLyThuocGUI();
    	quanlythuocgui.setVisible(true);
    }                                              

    private void label_quanlyhoadonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
    	this.setVisible(false);
    	QuanLyHoaDonGUI quanlyhoadongui = new QuanLyHoaDonGUI();
    	quanlyhoadongui.setVisible(true);
    	}                                               

    private void label_thongkeMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    	this.setVisible(false);
    	ThongKeDoanhThuGUI thongkedoanhthugui = new ThongKeDoanhThuGUI();
    	thongkedoanhthugui.setVisible(true);
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TongQuanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TongQuanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TongQuanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TongQuanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TongQuanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel icon_close_fullscreen;
    private javax.swing.JLabel label_thongke1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_fullscreen;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_quanlyhoadon;
    private javax.swing.JLabel label_quanlythuoc;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_tongquan;
    private javax.swing.JPanel panel_close;
    private javax.swing.JPanel panel_fullscreen;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_quanlyhoadon;
    private javax.swing.JPanel panel_quanlythuoc;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel panel_right_bot;
    private javax.swing.JPanel panel_right_top;
    private javax.swing.JPanel panel_thongke;
    private javax.swing.JPanel panel_thongso;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_tongquan;
    // End of variables declaration                   
}
